"""
DEFINITION OF DONE #1 -- no endpoint accepts a user identifier from the URL.

The important property of this file is that it does not enumerate routes by
hand. A hand-written list proves only that the routes someone remembered to
list are safe; the route added next week is exactly the one that will be
vulnerable. So the tests below walk the **live OpenAPI document** generated by
the running application and fail on anything that looks like a user identifier,
wherever it appears.

Three surfaces are checked, because the original vulnerability appeared on all
three:

    POST   /analyze/budget/{user_id}      <- path parameter
    POST   /ingest?user_id=...            <- query parameter
    POST   /chat  {"user_id": "..."}      <- request body

and one behavioural check, because schema shape alone is not proof: Alice's
token must not be able to read Bob's data through any route at all.
"""

from __future__ import annotations

import re
from typing import Any, Dict, Iterator, List, Tuple

import pytest

from main import app
from tests.conftest import login

# A parameter is suspect if it names a *subject* the caller could substitute.
# Deliberately broad -- false positives here are cheap and force a deliberate
# decision, while a false negative is an IDOR shipped to production.
SUSPECT = re.compile(
    r"^(user|owner|account_holder|customer|subject|principal|member)"
    r"[_-]?(id|uuid|guid|ref|handle|identifier)$"
    r"|^(uid|userid|user)$",
    re.IGNORECASE,
)

# Routes served by the framework itself, not by this application.
EXEMPT_PATHS = {"/openapi.json", "/docs", "/redoc", "/docs/oauth2-redirect"}


def openapi() -> Dict[str, Any]:
    return app.openapi()


def iter_operations() -> Iterator[Tuple[str, str, Dict[str, Any]]]:
    for path, item in openapi().get("paths", {}).items():
        if path in EXEMPT_PATHS:
            continue
        for method, operation in item.items():
            if method.lower() in {"get", "post", "put", "patch", "delete"}:
                yield path, method.upper(), operation


def resolve(schema: Dict[str, Any], spec: Dict[str, Any]) -> Dict[str, Any]:
    """Follow a single ``$ref`` into ``components.schemas``."""
    ref = schema.get("$ref")
    if not ref or not ref.startswith("#/components/schemas/"):
        return schema
    name = ref.rsplit("/", 1)[-1]
    return spec.get("components", {}).get("schemas", {}).get(name, {})


def walk_properties(schema: Dict[str, Any], spec: Dict[str, Any], depth: int = 0) -> Iterator[str]:
    """Yield every property name reachable from a request-body schema."""
    if depth > 6 or not isinstance(schema, dict):
        return
    schema = resolve(schema, spec)

    for name, sub in (schema.get("properties") or {}).items():
        yield name
        yield from walk_properties(sub, spec, depth + 1)

    for key in ("items", "additionalProperties"):
        if isinstance(schema.get(key), dict):
            yield from walk_properties(schema[key], spec, depth + 1)

    for key in ("allOf", "anyOf", "oneOf"):
        for sub in schema.get(key) or []:
            yield from walk_properties(sub, spec, depth + 1)


# ---------------------------------------------------------------------------
# Schema-level proofs
# ---------------------------------------------------------------------------


def test_no_path_or_query_parameter_names_a_user():
    """
    The original bug, stated as a test.

    ``POST /analyze/budget/{user_id}`` fails here on the path parameter;
    ``POST /ingest?user_id=`` fails on the query parameter.
    """
    offenders: List[str] = []
    for path, method, operation in iter_operations():
        for param in operation.get("parameters", []) or []:
            if SUSPECT.match(param.get("name", "")):
                offenders.append(
                    f"{method} {path} -> {param.get('in')} parameter " f"'{param.get('name')}'"
                )

    assert not offenders, (
        "User identifiers must come from the verified token, never the "
        "request. Offending parameters:\n  " + "\n  ".join(offenders)
    )


def test_no_request_body_carries_a_user_identifier():
    """``POST /chat {"user_id": ...}`` -- the third form of the same bug."""
    spec = openapi()
    offenders: List[str] = []

    for path, method, operation in iter_operations():
        body = operation.get("requestBody")
        if not body:
            continue
        for media_type, media in (body.get("content") or {}).items():
            schema = media.get("schema") or {}
            for prop in walk_properties(schema, spec):
                if SUSPECT.match(prop):
                    offenders.append(f"{method} {path} [{media_type}] -> '{prop}'")

    assert not offenders, (
        "Request bodies must not name their own subject. Offending "
        "properties:\n  " + "\n  ".join(offenders)
    )


def test_no_path_template_contains_an_identifier_segment():
    """
    Belt and braces.

    Catches ``/user/{id}`` and ``/users/{uuid}`` -- shapes where the parameter
    name alone ('id', 'uuid') would slip past a name-based filter but the
    surrounding path makes the subject unmistakable.
    """
    offenders: List[str] = []
    subject_words = {
        "user",
        "users",
        "customer",
        "customers",
        "member",
        "members",
        "account_holder",
        "profile",
        "profiles",
    }

    for path, method, _operation in iter_operations():
        segments = [s for s in path.split("/") if s]
        for i, seg in enumerate(segments):
            if seg.startswith("{") and i > 0 and segments[i - 1].lower() in subject_words:
                offenders.append(f"{method} {path} -> templated '{seg}' after '{segments[i-1]}'")

    assert not offenders, (
        "A templated segment directly under a subject collection is an IDOR "
        "by shape:\n  " + "\n  ".join(offenders)
    )


def test_every_data_route_declares_authentication():
    """
    Removing the parameter is not enough if the route is still anonymous.

    Only the routes listed as public may omit a security requirement; anything
    else must carry one, which FastAPI emits when the handler depends on the
    bearer scheme.
    """
    public = {
        ("/", "GET"),
        ("/health/live", "GET"),
        ("/health/ready", "GET"),
        ("/health/detailed", "GET"),
        ("/metrics", "GET"),
        ("/api/v1/health", "GET"),
        # Pre-authentication by definition.
        ("/api/v1/auth/register", "POST"),
        ("/api/v1/auth/login", "POST"),
        ("/api/v1/auth/refresh", "POST"),
        ("/api/v1/auth/mfa/verify", "POST"),
        # Called by the Account Aggregator, not by a user. Authenticated by
        # HMAC over the raw body instead of a bearer token -- see
        # test_aa_roundtrip.py::test_webhook_rejects_forged_signature.
        ("/api/v1/aa/webhooks/consent", "POST"),
        ("/api/v1/aa/webhooks/fi", "POST"),
        # /aa/sandbox/approve is deliberately NOT exempt: it stands in for the
        # user approving at their AA, and it requires a token like any other
        # route. Listing it here would have skipped the check.
        ("/api/v1/aa/info", "GET"),
    }

    unauthenticated: List[str] = []
    for path, method, operation in iter_operations():
        if (path, method) in public:
            continue
        if not operation.get("security"):
            unauthenticated.append(f"{method} {path}")

    assert (
        not unauthenticated
    ), "These routes serve or mutate user data without requiring a token:\n  " + "\n  ".join(
        unauthenticated
    )


def test_the_previously_vulnerable_routes_are_gone():
    """Named explicitly, so a regression is unmistakable in the failure output."""
    paths = set(openapi().get("paths", {}))
    for gone in [
        "/api/v1/analyze/budget/{user_id}",
        "/api/v1/analyze/summary/{user_id}",
        "/api/v1/analyze/forecast/{user_id}",
        "/api/v1/user/{user_id}",
        "/analyze/budget/{user_id}",
        "/analyze/summary/{user_id}",
        "/user/{user_id}",
    ]:
        assert gone not in paths, f"{gone} is still routed -- the IDOR is back"


# ---------------------------------------------------------------------------
# Behavioural proof
# ---------------------------------------------------------------------------


@pytest.mark.db
async def test_data_routes_reject_a_missing_token(client):
    """Unauthenticated access to a data route must be refused, not defaulted."""
    for method, path in [
        ("GET", "/api/v1/transactions"),
        ("GET", "/api/v1/analysis/summary"),
        ("GET", "/api/v1/analysis/budget"),
        ("GET", "/api/v1/analysis/anomalies"),
        ("GET", "/api/v1/stats"),
        ("DELETE", "/api/v1/me"),
    ]:
        response = await client.request(method, path)
        assert response.status_code in (401, 403), (
            f"{method} {path} returned {response.status_code} with no token; " f"expected 401/403"
        )


@pytest.mark.db
async def test_alice_cannot_reach_bobs_data_through_any_route(client, alice, bob):
    """
    The end-to-end statement of the property.

    Alice holds a valid token. There is no parameter she can supply -- and no
    route she can call -- that returns Bob's rows, because her session is bound
    to her id and RLS filters on it.
    """
    import uuid as _uuid

    from tests.test_rls_isolation import seed_transaction

    await login(alice)

    # Give Bob a transaction that Alice must never see.
    marker = f"BOB-SECRET-{_uuid.uuid4().hex[:8]}"
    await seed_transaction(bob.user_id, marker)

    # Every attempt Alice could make to name Bob.
    attempts = [
        ("GET", f"/api/v1/transactions?user_id={bob.user_id}", None),
        ("GET", f"/api/v1/analysis/summary?user_id={bob.user_id}", None),
        ("GET", f"/api/v1/transactions/{bob.user_id}", None),
        ("GET", f"/api/v1/analyze/summary/{bob.user_id}", None),
        ("DELETE", f"/api/v1/user/{bob.user_id}", None),
        ("POST", "/api/v1/chat", {"query": "show my spending", "user_id": str(bob.user_id)}),
    ]

    for method, path, body in attempts:
        response = await client.request(method, path, json=body, headers=alice.auth_header)
        assert marker not in response.text, (
            f"{method} {path} leaked Bob's data to Alice " f"(status {response.status_code})"
        )
        # 404 (no such route), 422 (unexpected field rejected), 200 with only
        # Alice's own rows, or 404 "no transactions" are all acceptable. A 200
        # containing the marker is not, and is caught above.
        assert response.status_code != 500, (
            f"{method} {path} returned 500 -- an unhandled error is not a " f"security control"
        )
