"""Initial FinGuru relational schema: identity, ledger, consent, ops.

Written by hand rather than autogenerated because three things Alembic cannot
express live here:

* ``transactions`` is RANGE-partitioned on ``txn_date``;
* every tenant table carries a Row-Level Security policy bound to the
  ``app.current_user_id`` session GUC;
* ``audit_log`` is append-only, enforced by trigger *and* by withholding
  UPDATE/DELETE grants from the application role.

Revision ID: 0001
Revises:
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.core.config import settings
from app.db.models import RLS_TABLES

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


APP_ROLE = settings.db_app_role
APP_PASSWORD = settings.db_app_password

# Partition coverage created up front. Anything outside the range lands in the
# DEFAULT partition, which is a correctness backstop, not a plan: the
# `ensure_transaction_partitions` maintenance function extends coverage.
PARTITION_START_YEAR = 2023
PARTITION_END_YEAR = 2028


def _create_app_role() -> None:
    """
    Create the non-superuser application role.

    RLS is silently bypassed for superusers and (unless FORCE is set) for the
    table owner. Running the application as a distinct, unprivileged grantee is
    therefore load-bearing, not hygiene.
    """
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                    CREATE ROLE {APP_ROLE} LOGIN PASSWORD '{APP_PASSWORD}';
                END IF;
                ALTER ROLE {APP_ROLE} NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
            END
            $$;
            """
        )
    )
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")


def upgrade() -> None:
    _create_app_role()

    # gen_random_uuid() is core since PostgreSQL 13, so no extension (and no
    # extra superuser privilege) is required.

    # ------------------------------------------------------------------
    # users
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE users (
            id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            email_ci           VARCHAR(320) NOT NULL UNIQUE,
            email_display      VARCHAR(320) NOT NULL,
            argon2_hash        VARCHAR(255) NOT NULL,
            mfa_secret_enc     TEXT,
            mfa_enabled        BOOLEAN NOT NULL DEFAULT false,
            mfa_confirmed_at   TIMESTAMPTZ,
            failed_login_count INTEGER NOT NULL DEFAULT 0,
            locked_until       TIMESTAMPTZ,
            is_active          BOOLEAN NOT NULL DEFAULT true,
            created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_users_email_ci_lowercase CHECK (email_ci = lower(email_ci))
        )
        """
    )
    op.execute("CREATE INDEX ix_users_locked_until ON users (locked_until)")

    # ------------------------------------------------------------------
    # refresh_tokens (rotating family with reuse detection)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE refresh_tokens (
            id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            family_id      UUID NOT NULL,
            parent_id      UUID,
            token_hash     VARCHAR(64) NOT NULL UNIQUE,
            issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at     TIMESTAMPTZ NOT NULL,
            used_at        TIMESTAMPTZ,
            revoked_at     TIMESTAMPTZ,
            revoked_reason VARCHAR(64),
            user_agent     VARCHAR(256),
            ip_address     INET
        )
        """
    )
    op.execute("CREATE INDEX ix_refresh_tokens_family_id ON refresh_tokens (family_id)")
    op.execute("CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id)")
    op.execute(
        "CREATE INDEX ix_refresh_tokens_live ON refresh_tokens (expires_at) "
        "WHERE revoked_at IS NULL"
    )

    # ------------------------------------------------------------------
    # categories (self-referencing hierarchy)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE categories (
            id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name      VARCHAR(64) NOT NULL,
            slug      VARCHAR(64) NOT NULL UNIQUE,
            parent_id UUID REFERENCES categories(id) ON DELETE SET NULL,
            is_income BOOLEAN NOT NULL DEFAULT false
        )
        """
    )
    op.execute("CREATE INDEX ix_categories_parent_id ON categories (parent_id)")

    # ------------------------------------------------------------------
    # accounts
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE accounts (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            aa_handle     VARCHAR(128) NOT NULL,
            masked_number VARCHAR(32) NOT NULL,
            fip_id        VARCHAR(64),
            type          VARCHAR(32) NOT NULL DEFAULT 'SAVINGS',
            currency      VARCHAR(3) NOT NULL DEFAULT 'INR',
            is_active     BOOLEAN NOT NULL DEFAULT true,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_accounts_id_user_id UNIQUE (id, user_id),
            CONSTRAINT uq_accounts_user_id_aa_handle UNIQUE (user_id, aa_handle),
            CONSTRAINT ck_accounts_currency_iso4217 CHECK (char_length(currency) = 3)
        )
        """
    )
    op.execute("CREATE INDEX ix_accounts_user_id ON accounts (user_id)")

    # ------------------------------------------------------------------
    # transactions -- RANGE partitioned on txn_date
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE transactions (
            id            UUID NOT NULL DEFAULT gen_random_uuid(),
            txn_date      DATE NOT NULL,
            account_id    UUID NOT NULL,
            user_id       UUID NOT NULL,
            amount_minor  BIGINT NOT NULL,
            currency      VARCHAR(3) NOT NULL DEFAULT 'INR',
            narration     TEXT NOT NULL,
            category_id   UUID REFERENCES categories(id) ON DELETE SET NULL,
            model_version VARCHAR(64),
            confidence    DOUBLE PRECISION,
            dedupe_hash   VARCHAR(64) NOT NULL,
            source        VARCHAR(16) NOT NULL DEFAULT 'aa',
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, txn_date),
            CONSTRAINT uq_transactions_dedupe UNIQUE (dedupe_hash, txn_date),
            CONSTRAINT ck_transactions_amount_nonzero CHECK (amount_minor <> 0),
            CONSTRAINT fk_transactions_account_user
                FOREIGN KEY (account_id, user_id)
                REFERENCES accounts (id, user_id) ON DELETE CASCADE
        ) PARTITION BY RANGE (txn_date)
        """
    )

    # Monthly partitions. Declared on the parent so every partition inherits
    # them; PostgreSQL creates the matching local index in each child.
    op.execute(
        """
        CREATE INDEX ix_transactions_account_date
            ON transactions (account_id, txn_date DESC)
            INCLUDE (amount_minor, narration, category_id)
        """
    )
    op.execute(
        "CREATE INDEX ix_transactions_user_date ON transactions (user_id, txn_date DESC)"
    )
    op.execute("CREATE INDEX ix_transactions_category_id ON transactions (category_id)")

    # Partition maintenance helper. Idempotent, so a cron job can call it
    # unconditionally.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ensure_transaction_partitions(
            months_ahead INTEGER DEFAULT 3
        ) RETURNS INTEGER AS $$
        DECLARE
            m        DATE := date_trunc('month', CURRENT_DATE)::DATE;
            i        INTEGER;
            created  INTEGER := 0;
            pname    TEXT;
            pstart   DATE;
            pend     DATE;
        BEGIN
            FOR i IN 0..months_ahead LOOP
                pstart := (m + (i || ' month')::INTERVAL)::DATE;
                pend   := (pstart + INTERVAL '1 month')::DATE;
                pname  := 'transactions_' || to_char(pstart, 'YYYY_MM');
                IF NOT EXISTS (
                    SELECT 1 FROM pg_class WHERE relname = pname
                ) THEN
                    EXECUTE format(
                        'CREATE TABLE %I PARTITION OF transactions '
                        'FOR VALUES FROM (%L) TO (%L)', pname, pstart, pend
                    );
                    created := created + 1;
                END IF;
            END LOOP;
            RETURN created;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    for year in range(PARTITION_START_YEAR, PARTITION_END_YEAR + 1):
        for month in range(1, 13):
            start = f"{year}-{month:02d}-01"
            end_year, end_month = (year + 1, 1) if month == 12 else (year, month + 1)
            end = f"{end_year}-{end_month:02d}-01"
            op.execute(
                f"CREATE TABLE transactions_{year}_{month:02d} "
                f"PARTITION OF transactions FOR VALUES FROM ('{start}') TO ('{end}')"
            )

    # Catch-all so an out-of-range date is a data-quality problem, not an
    # INSERT failure that loses a real transaction.
    op.execute(
        "CREATE TABLE transactions_default PARTITION OF transactions DEFAULT"
    )

    # ------------------------------------------------------------------
    # anomalies
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE anomalies (
            id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            txn_id           UUID NOT NULL,
            txn_date         DATE NOT NULL,
            user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            score            DOUBLE PRECISION NOT NULL,
            detector_version VARCHAR(64) NOT NULL,
            reviewed_at      TIMESTAMPTZ,
            review_outcome   VARCHAR(32),
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_anomalies_txn_detector UNIQUE (txn_id, detector_version),
            CONSTRAINT fk_anomalies_transaction
                FOREIGN KEY (txn_id, txn_date)
                REFERENCES transactions (id, txn_date) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_anomalies_unreviewed ON anomalies (user_id, score DESC) "
        "WHERE reviewed_at IS NULL"
    )
    op.execute("CREATE INDEX ix_anomalies_user_id ON anomalies (user_id)")

    # ------------------------------------------------------------------
    # consents / fi_sessions (Account Aggregator)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE consents (
            id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            aa_consent_id     VARCHAR(128) NOT NULL UNIQUE,
            aa_consent_handle VARCHAR(128),
            purpose_code      VARCHAR(8) NOT NULL,
            purpose_text      VARCHAR(256),
            scope             JSONB NOT NULL DEFAULT '{}'::jsonb,
            expiry            TIMESTAMPTZ NOT NULL,
            status            VARCHAR(16) NOT NULL DEFAULT 'PENDING',
            aa_provider       VARCHAR(32) NOT NULL DEFAULT 'setu',
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_consents_consent_status_enum CHECK (
                status IN ('PENDING','ACTIVE','REJECTED','REVOKED','PAUSED','EXPIRED')
            )
        )
        """
    )
    op.execute("CREATE INDEX ix_consents_user_id ON consents (user_id)")
    op.execute(
        "CREATE INDEX ix_consents_active ON consents (user_id, expiry) "
        "WHERE status = 'ACTIVE'"
    )

    op.execute(
        """
        CREATE TABLE fi_sessions (
            id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            consent_id       UUID NOT NULL REFERENCES consents(id) ON DELETE CASCADE,
            aa_session_id    VARCHAR(128) NOT NULL UNIQUE,
            status           VARCHAR(16) NOT NULL DEFAULT 'PENDING',
            from_date        DATE NOT NULL,
            to_date          DATE NOT NULL,
            records_ingested INTEGER NOT NULL DEFAULT 0,
            error            TEXT,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at     TIMESTAMPTZ
        )
        """
    )
    op.execute("CREATE INDEX ix_fi_sessions_user_id ON fi_sessions (user_id)")

    # ------------------------------------------------------------------
    # audit_log (append-only)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE audit_log (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            actor         VARCHAR(128) NOT NULL,
            actor_user_id UUID,
            action        VARCHAR(64) NOT NULL,
            resource      VARCHAR(128) NOT NULL,
            before        JSONB,
            after         JSONB,
            ip_address    INET,
            request_id    VARCHAR(64),
            at            TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_audit_log_actor_user_id_at ON audit_log (actor_user_id, at DESC)"
    )
    op.execute("CREATE INDEX ix_audit_log_action_at ON audit_log (action, at DESC)")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (attempted %)', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()
        """
    )

    # ------------------------------------------------------------------
    # outbox / idempotency / model registry
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE outbox_events (
            id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            aggregate_type VARCHAR(64) NOT NULL,
            aggregate_id   VARCHAR(128) NOT NULL,
            event_type     VARCHAR(64) NOT NULL,
            payload        JSONB NOT NULL,
            dedupe_key     VARCHAR(128) NOT NULL UNIQUE,
            created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
            available_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            processed_at   TIMESTAMPTZ,
            attempts       INTEGER NOT NULL DEFAULT 0,
            last_error     TEXT
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_outbox_pending ON outbox_events (available_at) "
        "WHERE processed_at IS NULL"
    )

    op.execute(
        """
        CREATE TABLE idempotency_keys (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            key           VARCHAR(128) NOT NULL UNIQUE,
            user_id       UUID,
            scope         VARCHAR(64) NOT NULL,
            request_hash  VARCHAR(64) NOT NULL,
            status_code   INTEGER,
            response_body JSONB,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at  TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_idempotency_keys_created_at ON idempotency_keys (created_at)"
    )

    op.execute(
        """
        CREATE TABLE model_registry (
            id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name              VARCHAR(64) NOT NULL,
            version           VARCHAR(64) NOT NULL,
            task              VARCHAR(32) NOT NULL,
            artifact_uri      TEXT,
            metrics           JSONB NOT NULL DEFAULT '{}'::jsonb,
            training_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
            is_active         BOOLEAN NOT NULL DEFAULT false,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_model_registry_name_version UNIQUE (name, version)
        )
        """
    )

    # ------------------------------------------------------------------
    # Row-Level Security
    # ------------------------------------------------------------------
    for table, column in RLS_TABLES.items():
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        # FORCE makes the policy apply to the table owner too, so a mistake in
        # ops tooling cannot quietly read across tenants either.
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING ({column}::text = current_setting('app.current_user_id', true))
            WITH CHECK ({column}::text = current_setting('app.current_user_id', true))
            """
        )
        # The migration owner needs unrestricted access for maintenance and
        # for the test harness's cross-tenant fixtures.
        op.execute(
            f"""
            CREATE POLICY {table}_owner_bypass ON {table}
            TO CURRENT_USER
            USING (current_setting('app.bypass_rls', true) = 'on')
            WITH CHECK (current_setting('app.bypass_rls', true) = 'on')
            """
        )

    # ------------------------------------------------------------------
    # Grants
    # ------------------------------------------------------------------
    op.execute(
        f"""
        GRANT SELECT, INSERT, UPDATE, DELETE ON
            users, refresh_tokens, categories, accounts, transactions,
            anomalies, consents, fi_sessions, outbox_events,
            idempotency_keys, model_registry
        TO {APP_ROLE}
        """
    )
    # audit_log: INSERT and SELECT only. No UPDATE, no DELETE, ever -- the
    # trigger is defence in depth behind the missing grant, not the only lock.
    op.execute(f"GRANT SELECT, INSERT ON audit_log TO {APP_ROLE}")
    op.execute(f"REVOKE UPDATE, DELETE ON audit_log FROM {APP_ROLE}")

    # RLS policies on a partitioned parent are enforced when rows are reached
    # *through the parent*, but NOT when a partition is addressed directly.
    # The application therefore gets no privileges on the partitions at all;
    # its only route to transaction rows is the parent, where the policy runs.
    # Partitions created later by ensure_transaction_partitions() inherit this
    # posture automatically, because no default privileges are granted.
    op.execute(
        f"""
        DO $$
        DECLARE t TEXT;
        BEGIN
            FOR t IN
                SELECT c.relname FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public'
                  AND c.relkind IN ('r', 'p')
                  AND c.relname LIKE 'transactions\\_%'
            LOOP
                EXECUTE format('REVOKE ALL ON %I FROM {APP_ROLE}', t);
            END LOOP;
        END
        $$;
        """
    )
    op.execute(f"GRANT EXECUTE ON FUNCTION ensure_transaction_partitions TO {APP_ROLE}")

    # ------------------------------------------------------------------
    # Narrow, audited privilege escalation for the AA webhook path
    # ------------------------------------------------------------------
    # An Account Aggregator notification arrives with only a session/consent
    # handle and no authenticated user, so the handler cannot open a tenant
    # session until it knows whose data it is -- but RLS hides the very row it
    # needs. Rather than granting a blanket bypass, these SECURITY DEFINER
    # functions disclose exactly one UUID each. The handler then opens a normal
    # tenant session and every subsequent statement is policed as usual.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION resolve_fi_session_owner(p_session_id TEXT)
        RETURNS UUID AS $$
            SELECT user_id FROM fi_sessions WHERE aa_session_id = p_session_id;
        $$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION resolve_consent_owner(p_consent_id TEXT)
        RETURNS UUID AS $$
            SELECT user_id FROM consents
            WHERE aa_consent_id = p_consent_id OR aa_consent_handle = p_consent_id
            LIMIT 1;
        $$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
        """
    )
    op.execute(f"GRANT EXECUTE ON FUNCTION resolve_fi_session_owner(TEXT) TO {APP_ROLE}")
    op.execute(f"GRANT EXECUTE ON FUNCTION resolve_consent_owner(TEXT) TO {APP_ROLE}")

    # ------------------------------------------------------------------
    # Seed the category hierarchy
    # ------------------------------------------------------------------
    op.execute(
        """
        INSERT INTO categories (name, slug, parent_id, is_income) VALUES
            ('Income',        'income',        NULL, true),
            ('Essentials',    'essentials',    NULL, false),
            ('Lifestyle',     'lifestyle',     NULL, false),
            ('Financial',     'financial',     NULL, false),
            ('Uncategorised', 'uncategorised', NULL, false)
        """
    )
    op.execute(
        """
        INSERT INTO categories (name, slug, parent_id, is_income)
        SELECT v.name, v.slug, p.id, v.is_income
        FROM (VALUES
            ('Salary',          'salary',          'income',     true),
            ('Interest',        'interest',        'income',     true),
            ('Refund',          'refund',          'income',     true),
            ('Groceries',       'groceries',       'essentials', false),
            ('Utilities',       'utilities',       'essentials', false),
            ('Rent',            'rent',            'essentials', false),
            ('Transport',       'transport',       'essentials', false),
            ('Healthcare',      'healthcare',      'essentials', false),
            ('Education',       'education',       'essentials', false),
            ('Dining',          'dining',          'lifestyle',  false),
            ('Entertainment',   'entertainment',   'lifestyle',  false),
            ('Shopping',        'shopping',        'lifestyle',  false),
            ('Travel',          'travel',          'lifestyle',  false),
            ('Investment',      'investment',      'financial',  false),
            ('Insurance',       'insurance',       'financial',  false),
            ('Loan EMI',        'loan_emi',        'financial',  false),
            ('Transfer',        'transfer',        'financial',  false),
            ('Fees & Charges',  'fees_charges',    'financial',  false)
        ) AS v(name, slug, parent_slug, is_income)
        JOIN categories p ON p.slug = v.parent_slug
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    op.execute("DROP FUNCTION IF EXISTS ensure_transaction_partitions(INTEGER)")
    op.execute("DROP FUNCTION IF EXISTS resolve_fi_session_owner(TEXT)")
    op.execute("DROP FUNCTION IF EXISTS resolve_consent_owner(TEXT)")
    for table in [
        "model_registry",
        "idempotency_keys",
        "outbox_events",
        "audit_log",
        "fi_sessions",
        "consents",
        "anomalies",
        "transactions",
        "accounts",
        "categories",
        "refresh_tokens",
        "users",
    ]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
